
import { Textarea } from "@/components/ui/textarea";
import { FormField, FormItem, FormLabel, FormControl, FormMessage } from "@/components/ui/form";
import { UseFormReturn } from "react-hook-form";
import { GraduationSpeechFormValues } from "@/utils/formSchema";

interface FinalTouchesTabProps {
  form: UseFormReturn<GraduationSpeechFormValues>;
}

const FinalTouchesTab = ({ form }: FinalTouchesTabProps) => {
  return (
    <div className="space-y-6">
      <FormField
        control={form.control}
        name="acknowledgements"
        render={({ field }) => (
          <FormItem>
            <FormLabel>Acknowledgements</FormLabel>
            <FormControl>
              <Textarea
                placeholder="List any family members, teachers, friends, mentors you want to acknowledge and any specific stories or anecdotes."
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="quote"
        render={({ field }) => (
          <FormItem>
            <FormLabel>Favorite Quote</FormLabel>
            <FormControl>
              <Textarea
                placeholder="Share a quote that inspires you"
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="wishes"
        render={({ field }) => (
          <FormItem>
            <FormLabel>What are some wishes for the graduating students?</FormLabel>
            <FormControl>
              <Textarea
                placeholder="While this section is optional, providing details can greatly enhance the quality of the speech generated by the AI."
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="additionalInfo"
        render={({ field }) => (
          <FormItem>
            <FormLabel>Additional Information</FormLabel>
            <FormControl>
              <Textarea
                placeholder="Any other details that might help create your perfect speech"
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />
    </div>
  );
};

export default FinalTouchesTab;
