
import { Textarea } from "@/components/ui/textarea";
import { FormField, FormItem, FormLabel, FormControl, FormMessage } from "@/components/ui/form";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { UseFormReturn } from "react-hook-form";
import { GraduationSpeechFormValues } from "@/utils/formSchema";
import { Asterisk } from "lucide-react";

interface SpeechDetailsTabProps {
  form: UseFormReturn<GraduationSpeechFormValues>;
}

const SpeechDetailsTab = ({ form }: SpeechDetailsTabProps) => {
  return (
    <div className="space-y-6">
      <FormField
        control={form.control}
        name="tone"
        render={({ field }) => (
          <FormItem>
            <FormLabel className="flex items-center">
              Desired Tone
              <Asterisk className="h-3 w-3 text-red-500 ml-1" />
            </FormLabel>
            <Select onValueChange={field.onChange} defaultValue={field.value}>
              <FormControl>
                <SelectTrigger>
                  <SelectValue placeholder="Select the tone for your speech" />
                </SelectTrigger>
              </FormControl>
              <SelectContent>
                <SelectItem value="Formal & elevated">Formal & elevated</SelectItem>
                <SelectItem value="Encouraging & supportive">Encouraging & supportive</SelectItem>
                <SelectItem value="Reflective & motivational">Reflective & motivational</SelectItem>
                <SelectItem value="Uplifting & inspirational">Uplifting & inspirational</SelectItem>
              </SelectContent>
            </Select>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="memories"
        render={({ field }) => (
          <FormItem>
            <FormLabel>Share a standout moment or event during your academic journey.</FormLabel>
            <FormControl>
              <Textarea
                placeholder="While this section is optional, providing details can greatly enhance the quality of the speech generated by the AI"
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />
  
      <FormField
        control={form.control}
        name="themes"
        render={({ field }) => (
          <FormItem>
            <FormLabel>
              Are there any particular themes or messages you want included in your speech?
            </FormLabel>
            <FormControl>
              <Textarea
                placeholder="While this section is optional, providing details can greatly enhance the quality of the speech generated by the AI."
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="personalBackground"
        render={({ field }) => (
          <FormItem>
            <FormLabel>
              Please share a bit about your personal background (experiences, family, cultural heritage) and how it has shaped your journey.
            </FormLabel>
            <FormControl>
              <Textarea
                placeholder="While this section is optional, providing details can greatly enhance the quality of the speech generated by the AI."
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="goalsLessons"
        render={({ field }) => (
          <FormItem>
            <FormLabel>
              What are some goals you accomplished and what are some lessons you learnt? Describe any significant challenges you faced and overcame during your studies.
            </FormLabel>
            <FormControl>
              <Textarea
                placeholder="While this section is optional, providing details can greatly enhance the quality of the speech generated by the AI."
                className="min-h-[100px]"
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />
    </div>
  );
};

export default SpeechDetailsTab;
